# cmake -DINPUT=<file> -DOUTPUT=<header> -DSYMBOL=<name> -P EmbedFile.cmake
# Writes <file> as a C byte array, 16 bytes per line.
file(READ "${INPUT}" content HEX)
string(LENGTH "${content}" hex_length)
math(EXPR byte_count "${hex_length} / 2")

set(body "")
set(offset 0)
while(offset LESS hex_length)
    string(SUBSTRING "${content}" ${offset} 32 chunk)  # 32 hex chars = 16 bytes
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," chunk "${chunk}")
    string(APPEND body "    ${chunk}\n")
    math(EXPR offset "${offset} + 32")
endwhile()

file(WRITE "${OUTPUT}"
"// Generated by cmake/EmbedFile.cmake from ${INPUT}. Do not edit.\n"
"#pragma once\n"
"static const unsigned char ${SYMBOL}[] = {\n${body}};\n"
"static const unsigned long long ${SYMBOL}_size = ${byte_count}ull;\n")
